#define L_PINKY_O COMMA
#define L_PINKY_U B
#define L_PINKY_H N
#define L_PINKY_B K
#define L_RING_U L
#define L_RING_H R
#define L_RING_B Q
#define L_MID_U D
#define L_MID_H T
#define L_MID_B M
#define L_INDEX_U C
#define L_INDEX_H S
#define L_INDEX_B W
#define L_INDEX_R V
#define L_INDEX_T G
#define R_PINKY_O DOT
#define R_PINKY_U Z
#define R_PINKY_H I
#define R_PINKY_B X
#define R_RING_U U
#define R_RING_H E
#define R_RING_B SEMICOLON
#define R_MID_U O
#define R_MID_H A
#define R_MID_B SLASH
#define R_INDEX_U Y
#define R_INDEX_H H
#define R_INDEX_B F
#define R_INDEX_R J
#define R_INDEX_T P
